#!/usr/bin/env bash
# Record the images the cluster actually pulled, per architecture.
#
# The manifests pin multi-architecture index digests. This writes down what was
# really resolved on this machine, so "pinned and reproducible" is an observed
# fact rather than an assumption about what the registry served.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$REPO_ROOT/infra/local/IMAGES.md"

{
  echo "# Images actually pulled"
  echo
  echo "Generated by \`scripts/record-images.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "Host architecture: \`$(uname -m)\`"
  echo
  echo "## kind node image"
  echo
  echo '```'
  kind version
  echo '```'
  echo
  echo "| Node | Image | Node architecture | Kubelet |"
  echo "| --- | --- | --- | --- |"
  kubectl get nodes -o json 2>/dev/null | jq -r '
    .items[] |
    "| \(.metadata.name) | \(.status.nodeInfo.osImage) | \(.status.nodeInfo.architecture) | \(.status.nodeInfo.kubeletVersion) |"
  ' || echo "| (cluster not reachable) | | | |"
  echo
  echo "## Container images resolved in the cluster"
  echo
  echo "\`image\` is what the manifest requested; \`imageID\` is the digest the"
  echo "node actually resolved for its own architecture."
  echo
  echo "| Namespace | Pod | Requested image | Resolved imageID |"
  echo "| --- | --- | --- | --- |"
  kubectl get pods -A -o json 2>/dev/null | jq -r '
    .items[] | .metadata as $m | (.status.containerStatuses // [])[] |
    "| \($m.namespace) | \($m.name) | `\(.image)` | `\(.imageID)` |"
  ' | sort || echo "| (cluster not reachable) | | | |"
} > "$OUT"

echo "  wrote $OUT"
